[versions]
kotlin = "2.2.21"
kotlin-coroutines = "1.10.2"
kotlin-result = "2.1.0"
mockk = "1.14.7"
versions-plugin = "0.53.0"
maven-publish-plugin = "0.34.0"

[libraries]
kotlin-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlin-coroutines" }
kotlin-coroutines-test = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-test", version.ref = "kotlin-coroutines" }
kotlin-result = { module = "com.michael-bull.kotlin-result:kotlin-result", version.ref = "kotlin-result" }
mockk = { module = "io.mockk:mockk", version.ref = "mockk" }

# buildSrc subproject
kotlin-gradle-plugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
maven-publish-plugin = { module = "com.vanniktech.maven.publish:com.vanniktech.maven.publish.gradle.plugin", version.ref = "maven-publish-plugin" }

[plugins]
versions = { id = "com.github.ben-manes.versions", version.ref = "versions-plugin" }
